version: '3.7'

services:
  postgres:
    image: postgres:14.4
    container_name: pgdb_container
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USR}
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_DB: ${PG_DB}
      PGDATA: /var/lib/postgresql/data/pgdata

