version: '3.9'

services:
  postgres_dev:
    image: postgres:14.4
    container_name: 'postgres_dev'
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USR}
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_DB: ${PG_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - local-dev-net

networks:
    local-dev-net:
      external: true
      name: local-dev-net

